// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitzam.Server.Data;

#nullable disable

namespace Pitzam.Server.Migrations
{
    [DbContext(typeof(PizzaStoreContext))]
    [Migration("20260109141634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pitzam.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Pitzam.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PizzaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemovedIngredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pitzam.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Klasik İtalyan lezzeti. Domates sosu, taze mozzarella ve fesleğen.",
                            ImageUrl = "images/margherita.jpg",
                            Ingredients = "[\"Mozzarella\",\"Domates Sosu\",\"Fesle\\u011Fen\"]",
                            Name = "Margherita"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bol pepperoni ve mozzarella peyniri ile acı sevenlere özel.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Domates Sosu\",\"Pepperoni\"]",
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Taze sebzelerle dolu. Biber, mantar, zeytin ve mozzarella.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Domates Sosu\",\"Biber\",\"Mantar\",\"Zeytin\"]",
                            Name = "Vejetaryen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Geleneksel lezzet. Bol sucuk, mozzarella ve domates sosu.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Domates Sosu\",\"Sucuk\"]",
                            Name = "Sucuklu"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Özel barbekü sosu, tavuk parçaları ve soğan ile dumanlı lezzet.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"BBQ Sosu\",\"Tavuk\",\"So\\u011Fan\"]",
                            Name = "Tavuklu BBQ"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tam bir peynir şöleni. Mozzarella, cheddar, parmesan ve beyaz peynir.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Cheddar\",\"Parmesan\",\"Beyaz Peynir\"]",
                            Name = "Dört Peynirli"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Denizden gelen lezzet. Ton balığı, zeytin, mısır ve mozzarella.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Ton Bal\\u0131\\u011F\\u0131\",\"Zeytin\",\"M\\u0131s\\u0131r\"]",
                            Name = "Ton Balıklı"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Güçlü bir Anadolu tadı. Kavurma, soğan ve mozzarella.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Domates Sosu\",\"Kavurma\",\"So\\u011Fan\"]",
                            Name = "Kavurmalı"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Deniz tutkunlarına özel. Karides, kalamar ve sarımsaklı sos.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Karides\",\"Kalamar\",\"Sar\\u0131msak\"]",
                            Name = "Deniz Mahsullü"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Acı ve lezzetli bir macera. Jalapeno, mısır ve kırmızı biber.",
                            ImageUrl = "images/pizza.jpg",
                            Ingredients = "[\"Mozzarella\",\"Jalapeno\",\"M\\u0131s\\u0131r\",\"K\\u0131rm\\u0131z\\u0131 Biber\"]",
                            Name = "Meksika"
                        });
                });

            modelBuilder.Entity("Pitzam.Models.PizzaSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PizzaId = 1,
                            Price = 120.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 2,
                            PizzaId = 1,
                            Price = 156.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 3,
                            PizzaId = 1,
                            Price = 192.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 4,
                            PizzaId = 2,
                            Price = 140.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 5,
                            PizzaId = 2,
                            Price = 182.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 6,
                            PizzaId = 2,
                            Price = 224.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 7,
                            PizzaId = 3,
                            Price = 130.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 8,
                            PizzaId = 3,
                            Price = 169.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 9,
                            PizzaId = 3,
                            Price = 208.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 10,
                            PizzaId = 4,
                            Price = 150.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 11,
                            PizzaId = 4,
                            Price = 195.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 12,
                            PizzaId = 4,
                            Price = 240.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 13,
                            PizzaId = 5,
                            Price = 155.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 14,
                            PizzaId = 5,
                            Price = 201.50m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 15,
                            PizzaId = 5,
                            Price = 248.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 16,
                            PizzaId = 6,
                            Price = 160.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 17,
                            PizzaId = 6,
                            Price = 208.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 18,
                            PizzaId = 6,
                            Price = 256.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 19,
                            PizzaId = 7,
                            Price = 150.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 20,
                            PizzaId = 7,
                            Price = 195.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 21,
                            PizzaId = 7,
                            Price = 240.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 22,
                            PizzaId = 8,
                            Price = 170.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 23,
                            PizzaId = 8,
                            Price = 221.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 24,
                            PizzaId = 8,
                            Price = 272.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 25,
                            PizzaId = 9,
                            Price = 180.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 26,
                            PizzaId = 9,
                            Price = 234.00m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 27,
                            PizzaId = 9,
                            Price = 288.00m,
                            Size = "Büyük"
                        },
                        new
                        {
                            Id = 28,
                            PizzaId = 10,
                            Price = 165.00m,
                            Size = "Küçük"
                        },
                        new
                        {
                            Id = 29,
                            PizzaId = 10,
                            Price = 214.50m,
                            Size = "Orta"
                        },
                        new
                        {
                            Id = 30,
                            PizzaId = 10,
                            Price = 264.00m,
                            Size = "Büyük"
                        });
                });

            modelBuilder.Entity("Pitzam.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pitzam.Models.Customer", b =>
                {
                    b.HasOne("Pitzam.Models.User", null)
                        .WithMany("SavedAddresses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Pitzam.Models.Order", b =>
                {
                    b.HasOne("Pitzam.Models.Customer", "CustomerInfo")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("CustomerInfo");
                });

            modelBuilder.Entity("Pitzam.Models.PizzaSize", b =>
                {
                    b.HasOne("Pitzam.Models.Pizza", "Pizza")
                        .WithMany("Sizes")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("Pitzam.Models.Pizza", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Pitzam.Models.User", b =>
                {
                    b.Navigation("SavedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
